aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/dns-operator-route53"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io

pod:
  user:
    id: 1000
  group:
    id: 1000

# necessary for RBACs
# provider:
#   kind: e.g. openstack, cloud-director
