aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/dns-operator-route53"
  tag: "[[ .Version ]]"
registry:
  domain: gsoci.azurecr.io

pod:
  user:
    id: 1000
  group:
    id: 1000
  resources:
    limits:
      memory: 200Mi
    requests:
      memory: 200Mi

# necessary for RBACs
# provider:
#   kind: e.g. openstack, cloud-director

# Base domain for DNS records.
baseDomain: ""

# Name of management cluster. Used in comments of DNS records to track WC->MC relation.
managementCluster: ""

# Role ARN to assume for AWS API calls
roleARN: ""

# IP address of bastion machine for all clusters
staticBastionIP: ""

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

global:
  podSecurityStandards:
    enforced: false
